
CC = arm-none-eabi-
CFLAGS = -mcpu=cortex-m3 -gdwarf-2
INCS = -I .
LIBS =

SRC = $(wildcard *.c)
OBJ =  $(SRC:.c=.o)

SymbolosExplainer = PYcommon/ExplainSymbols.py

ProjectName = CortexM3


all: $(ProjectName).bin ExplainSymbols
	@echo "Build Done"



%.o: %.c
	@$(CC)gcc.exe $(CFLAGS) $(INCS) -c $< -o $@
	@$(CC)nm.exe $@ > $(basename $(@))_Symbols.txt
	@echo $<


$(ProjectName).elf: $(OBJ)
	@$(CC)ld.exe -T linker.ld $(LIBS) $(OBJ) -o $@ -Map=MapFile.map
	@echo "Generated $@"
	
	
$(ProjectName).bin: $(ProjectName).elf
	@$(CC)objcopy.exe -O binary $< $@
	@echo "Generated $@"


ExplainSymbols: 
	@$(system) python $(SymbolosExplainer)



clean:
	@rm -f *.o *.elf *.hex *.bin *.map *Symbols.txt *_Symbols_Explained.txt
	@echo "Removed all binary, elf, symbols and object files"